/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./pages/**/*.{js,ts,jsx,tsx}",
    "./Components/**/*.{js,ts,jsx,tsx}",
    "./app/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      fontFamily: {
        'shadows-into-light': ['"Shadows Into Light"', 'cursive'],
      },
      colors: {
        base100: '#16161a',
        base200: '#141418',
        base300: '#121214',
        baseContent: '#cbd5e1',
        primary: '#e63946',
        primaryContent: '#2a2a2a',
        secondary: '#f1faee',
        secondaryContent: '#2a2a2a',
        accent: '#a8dadc',
        accentContent: '#2a2a2a',
        neutral: '#3a3a3a',
        neutralContent: '#cbd5e1',
        info: '#457b9d',
        infoContent: '#f1faee',
        success: '#2a9d8f',
        successContent: '#f1faee',
        warning: '#f4a261',
        warningContent: '#2a2a2a',
        error: '#e76f51',
        errorContent: '#2a2a2a',
      },
    },
  },
  plugins: [require("daisyui")],
  daisyui: {
    themes: [
      {
        sunset: {
          primary: '#e63946',
          'primary-content': '#2a2a2a',
          secondary: '#f1faee',
          'secondary-content': '#2a2a2a',
          accent: '#a8dadc',
          'accent-content': '#2a2a2a',
          neutral: '#3a3a3a',
          'neutral-content': '#cbd5e1',
          'base-100': '#16161a',
          'base-content': '#cbd5e1',
          info: '#457b9d',
          'info-content': '#f1faee',
          success: '#2a9d8f',
          'success-content': '#f1faee',
          warning: '#f4a261',
          'warning-content': '#2a2a2a',
          error: '#e76f51',
          'error-content': '#2a2a2a',
        },
      },
    ],
    darkTheme: 'sunset',
  },
};
